import type { Metadata } from 'next'
import { Be_Vietnam_Pro, Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'

const vietnamSerif = Be_Vietnam_Pro({
  variable: '--font-serif-vietnam',
  subsets: ['latin'],
  weight: ['500']
})

const jakartaSans = Plus_Jakarta_Sans({
  variable: '--font-sans-jakarta',
  subsets: ['latin'],
  weight: ['400', '600', '700', '800']
})

export const metadata: Metadata = {
  title: 'Test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${vietnamSerif.variable} ${jakartaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
